---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-name
spec:
  selector:
    app: hello-link-to-service
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 9080
      # Port to forward to inside POD
      targetPort: 9080
      # Port accessible outside cluster
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-link-to-service
  template:
    metadata:
      labels:
        app: hello-link-to-service
    spec:
      containers:
        - name: hello-container
          image: jagadeeshdockerk/mydockerrepo:dt090419
          ports:
            - containerPort: 9080
